### ISSUE TITLE
$firebase is deprecated in AngularFire 1.0

### ISSUE THREAD

**Issue by fuczak** [leotrieu/Code4Startup.Ninja#5]
There should be a note somewhere clearly stating that >=1.0 version of AngularFire is incompatible with this tutorial.

**Comment by leotrieu** [comment]
I thought I already mentioned in the video (can't remember exactly which one) that this tutorial strictly should be used with the exact version of all dependencies.

Normally, students should follow exact requirements for such a tutorial. Otherwise, things will be messed up. Rails dependencies are another example.

But an updated note is not killing anyone.

**Comment by fuczak** [comment]
Oh, okay. I might have missed that.
